config/routes.rb
Rails.application.routes.draw do
  resources :pius
  devise_for :users
  root 'pages#index'
  resources :parties do
    collection do
        post :add_student
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/party.rb
class Party < ApplicationRecord
    has_attached_file :image
    validates_attachment_content_type :image, content_type: /\Aimage/

    has_and_belongs_to_many :users
end

app/models/piu.rb
class Piu < ApplicationRecord
  belongs_to :user

    validates :user, presence: true
    validates :content, presence: true, length: { maximum: 140 }

    has_attached_file :photo
    do_not_validate_attachment_file_type :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


         has_many :pius

             has_and_belongs_to_many :parties

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  # before_action :set_party, only: [:show, :edit, :update, :destroy]
before_action :authenticate_user!

def add_student

    @party = Party.find(params[:party_id])
    student = User.find_by(email: params[:email])

    begin
        @party.users << student
        @party.save

        message = "Temos um novo aluno em nossa party"
    rescue
        message = "Não rolou de colocar o novo aluno em nossa party"
    end

    redirect_back fallback_location: root_path, alert:message
end

  # GET /parties
  # GET /parties.json
  def index
    @parties = Party.all
  end

  # GET /parties/1
  # GET /parties/1.json
  def show
    set_party
  end

  # GET /parties/new
  def new
    @party = Party.new
  end

  # GET /parties/1/edit
  def edit
    set_party
  end

  # POST /parties
  # POST /parties.json
  def create
    @party = Party.new(party_params)

    respond_to do |format|
      if @party.save
        format.html { redirect_to @party, notice: 'Party was successfully created.' }
        format.json { render :show, status: :created, location: @party }
      else
        format.html { render :new }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parties/1
  # PATCH/PUT /parties/1.json
  def update
    respond_to do |format|
      if @party.update(party_params)
        format.html { redirect_to @party, notice: 'Party was successfully updated.' }
        format.json { render :show, status: :ok, location: @party }
      else
        format.html { render :edit }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parties/1
  # DELETE /parties/1.json
  def destroy
    set_party
    @party.destroy
    respond_to do |format|
      format.html { redirect_to parties_url, notice: 'Party was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_party
      @party = Party.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def party_params
      params.require(:party).permit(:name, :begin, :end, :hours, :image)
    end
end

app/controllers/pius_controller.rb
class PiusController < ApplicationController
  before_action :authenticate_user!

  # GET /pius
  # GET /pius.json
  def index
    @pius = Piu.all
  end

  # GET /pius/1
  # GET /pius/1.json
  def show
    @piu = Piu.find(params[:id])
  end

  # GET /pius/new
  def new
    @piu = current_user.pius.new
  end

  # GET /pius/1/edit
  def edit
    @piu = current_user.pius.find(params[:id])
  end

  # POST /pius
  # POST /pius.json
  def create
    @piu = current_user.pius.new(piu_params)

    respond_to do |format|
      if @piu.save
        format.html { redirect_to @piu, notice: 'Piu was successfully created.' }
        format.json { render :show, status: :created, location: @piu }
      else
        format.html { render :new }
        format.json { render json: @piu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pius/1
  # PATCH/PUT /pius/1.json
  def update
    @piu = current_user.pius.find(params[:id])
    respond_to do |format|
      if @piu.update(piu_params)
        format.html { redirect_to @piu, notice: 'Piu was successfully updated.' }
        format.json { render :show, status: :ok, location: @piu }
      else
        format.html { render :edit }
        format.json { render json: @piu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pius/1
  # DELETE /pius/1.json
  def destroy
    @piu = current_user.pius.find(params[:id])
    @piu.destroy
    respond_to do |format|
      format.html { redirect_to pius_url, notice: 'Piu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_piu
      @piu = Piu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def piu_params
      params.require(:piu).permit(:user_id, :content, :photo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/helpers/pius_helper.rb
module PiusHelper
end

app/helpers/pós_helper.rb
module PósHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClassGeek</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-custom bg-custom">
        <div class="container">
    <%= link_to "ClassGeek", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
        <%= link_to "Grupos", parties_path, class: "nav-item nav-link" %>
                <%= link_to "Pius", pius_path, class: "nav-item nav-link" %>

        </div>
      </div>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav  ml-auto">
        <% if !user_signed_in? %>
            <%= link_to "Cadastrar",  new_user_registration_path, class: "btn btn-primary mr-3" %>
            <%= link_to "Entrar",  new_user_session_path, class: "btn btn-info" %>
        <% else %>
            <%= link_to "Sair", destroy_user_session_path, :method=> :delete, class: "btn btn-danger" %>
        <% end %>
        </div>
      </div>
     </div>
    </nav>

    <% flash.each do |name, message| %>
        <%= content_tag(:div, message, class: "alert alert-info") %>
    <% end %>

    <div class="container">
        <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<div class="jumbotron margin mt-5">
  <h1 class="display-4">Seja Bem-vindo!!</h1>
  <p class="lead">Esta é uma rede social mto top (Cópia do tuiter) e original</p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <%= link_to "Cadastre-se",  new_user_registration_path, class: "btn btn-info" %>
</div>

app/views/parties/_form.html.erb
<%= form_with(model: party, local: true) do |form| %>
  <% if party.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(party.errors.count, "error") %> prohibited this party from being saved:</h2>

      <ul>
        <% party.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :begin %>
    <%= form.datetime_select :begin %>
  </div>

  <div class="field">
    <%= form.label :end %>
    <%= form.datetime_select :end %>
  </div>

  <div class="field">
    <%= form.label :hours %>
    <%= form.text_field :hours %>
  </div>

    <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/parties/edit.html.erb
<h1>Editing Party</h1>

<%= render 'form', party: @party %>

<%= link_to 'Show', @party %> |
<%= link_to 'Back', parties_path %>

app/views/parties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Parties</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Begin</th>
      <th>End</th>
      <th>Hours</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parties.each do |party| %>
      <tr>
        <td><%= party.name %></td>
        <td><%= party.begin %></td>
        <td><%= party.end %></td>
        <td><%= party.hours %></td>
        <td><%= link_to 'Show', party %></td>
        <td><%= link_to 'Edit', edit_party_path(party) %></td>
        <td><%= link_to 'Destroy', party, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Party', new_party_path %>

app/views/parties/new.html.erb
<h1>New Party</h1>

<%= render 'form', party: @party %>

<%= link_to 'Back', parties_path %>

app/views/parties/show.html.erb
<div class="row mt-5">
    <div class="col-4">
        <div class="card" style="width: 18rem;">
            <%= image_tag @party.image.url, class: "card-img-top" %>
            <div class="card-body">
                <h5 class="card-title"><%= @party.name %></h5>
                <h6 class="card-subtitle mb-2 text-muted"><%= @party.begin.strftime("%id/%m/%Y") %> ~ <%= @party.end.strftime("%id/%m/%Y") %></h6>
                <h6 class="card-subtitle mb-2 text-muted"><%= @party.hours %></h6>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <a href="#" class="btn btn-primary">Go somewhere</a>
            </div>
        </div>
    </div>

    <div class="col-8">
        <%= form_tag add_student_parties_path(@party), :method => :post do %>
            <%= email_field_tag :email %>
            <%= hidden_field_tag :party_id, @party.id %>
            <%= submit_tag "Adicionar" %>
        <% end %>

        <div class="card">
            <div class="card-body">
                <!-- ALUNOS -->
                <% @party.users.each do |student| %>
                    <div class="card">
                        <div class="card-body">
                            <%= student.name %>
                        </div>
                    </div>
                <% end %>
            </div>
            </div>
        </div>
    </div>
</div>


<%= link_to 'Edit', edit_party_path(@party) %> |
<%= link_to 'Back', parties_path %>

app/views/pius/_form.html.erb
<%= form_with(model: piu, local: true) do |form| %>
  <% if piu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(piu.errors.count, "error") %> prohibited this piu from being saved:</h2>

      <ul>
        <% piu.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :photo, "Adicionar Imagem" %>
    <%= form.file_field :photo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pius/edit.html.erb
<h1>Editing Piu</h1>

<%= render 'form', piu: @piu %>

<%= link_to 'Show', @piu %> |
<%= link_to 'Back', pius_path %>

app/views/pius/index.html.erb
<div class="row mt-5">
    <div class="col-4">
        <div class="card" style="width: 18rem;">
        <% url = Gravatar.new(current_user.email).image_url %>
        <%= image_tag url, class: "card-img-top" %>
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>
    </div>
    <div class="col-8">
        <h1>Pius</h1>

        <table>
        <thead>
            <tr>
            <th>User</th>
            <th>Content</th>
            <th colspan="3"></th>
            </tr>
        </thead>

        <tbody>
            <% @pius.order(id: :desc).each do |piu| %>
            <tr>
                <td><%= piu.user.email %></td>
                <td><%= piu.content %>
                <td>
                    <% if piu.photo.file? %>
                        <%= image_tag piu.photo.url, class: "rounded-lg mb-3 img-size-limit" %>
                    <% end %>
                </td>
                <p class="card-text">
                    <small class="text-muted">
                        <%= piu.created_at.strftime("%d/%m/%Y - %H:%M") %>
                    </small>
                </p>
                </td>
                <td><%= link_to 'Show', piu %></td>
                <% if current_user == piu.user %>
                <td><%= link_to 'Edit', edit_piu_path(piu) %></td>
                <td><%= link_to 'Destroy', piu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                <% end %>
            </tr>
            <% end %>
        </tbody>
        </table>

        <br>

        <%= link_to 'New Piu', new_piu_path %>

    </div>
</div>

<p id="notice"><%= notice %></p>

app/views/pius/new.html.erb
<h1>New Piu</h1>

<%= render 'form', piu: @piu %>

<%= link_to 'Back', pius_path %>

app/views/pius/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @piu.user_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @piu.content %>
</p>

<%= link_to 'Edit', edit_piu_path(@piu) %> |
<%= link_to 'Back', pius_path %>

app/views/pós/_form.html.erb
<%= form_with(model: pó, local: true) do |form| %>
  <% if pó.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pó.errors.count, "error") %> prohibited this pó from being saved:</h2>

      <ul>
        <% pó.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pós/edit.html.erb
<h1>Editing Pó</h1>

<%= render 'form', pó: @pó %>

<%= link_to 'Show', @pó %> |
<%= link_to 'Back', pós_path %>

app/views/pós/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pós</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pós.each do |pó| %>
      <tr>
        <td><%= link_to 'Show', pó %></td>
        <td><%= link_to 'Edit', edit_pó_path(pó) %></td>
        <td><%= link_to 'Destroy', pó, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pó', new_pó_path %>

app/views/pós/new.html.erb
<h1>New Pó</h1>

<%= render 'form', pó: @pó %>

<%= link_to 'Back', pós_path %>

app/views/pós/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_pó_path(@pó) %> |
<%= link_to 'Back', pós_path %>